### ISSUE TITLE
cli API

### ISSUE THREAD

**Issue by darribas** [conjuring/conjuring#39] opened 2019-09-04 09:47 UTC
Hey @casperdcl, I've drafted up a note describing a workflow that relies mostly on what we have already, but requires  couple of additions (cli interface and the `custom.json` option). The note is on the wiki, here:

> [https://github.com/conjuring/conjuring/wiki/CLI-workflow](https://github.com/conjuring/conjuring/wiki/CLI-workflow)

How hard do you think it'd be to implement what is not available already?

**Comment by casperdcl** [comment] 2019-09-04 09:49
duplicate of #20

**Comment by darribas** [comment] 2019-09-04 09:52
Actually, not quite. The `pip` installation does relate to #20, the `custom.json` does not at all and it's an important bit of my question.

**Comment by casperdcl** [comment] 2019-09-04 11:48
I think it's best to integrate it with #20 as this issue (#39) is really what I meant #20 to be (the pip install stuff was just really a side note).

**Comment by casperdcl** [comment] 2019-09-04 12:04
@darribas just updated #20 to make it more clear. If you think #39 is different please re-open!

**Closed by casperdcl** 2019-09-04 12:04 UTC
Labels: enhancement

**Comment by jreades** [comment] 2019-09-04 17:19
Some comments/thoughts:


1. Is there any reason to have a —dest parameter to conjuring project? Intuitively, anything without an explicitly flag (e.g. —foo bar) would be the name of a project and would used elsewhere in the setup (to create the folder, to set the image name…)? So I would suggest simplest format is: conjuring project ectqg2019, which would create your conjuring template in a directory called ectqg2019. And add the appropriate metadata. You could still run conjuring project which would create a conjuring dir and set the Docker container name to conjuring...

2. Minor note: do we want to tell people to edit the base.Dockerfile (current just Dockerfile right?)? Or do we want to encourage them to look at the Conjuring site/Wiki to get a sense of what’s available and, ideally, use a pre-existing file?

3. A gallery for existing deployments [not for first release]

4. Be able to change the name of the ‘latest’ container to avoid namespace clashes if you’re trying to prepare two different workshops at the same time [not for first release, necessarily, but would be rather useful bit of functionality.]


--
m: 07976987392
e: jon@reades.com
s: jreades

**Comment by szschaler** [comment] 2019-09-05 08:54
I think, your last point will sort itself out. I believe docker-compose sets up distinct containers anyway when it’s run in different directories. (might be worth double-checking, though)

Steffen

Dr. rer. nat. Steffen Zschaler AHEA

Senior Lecturer
King's College London
Department of Informatics

Visiting Scientist
The Francis Crick Institute

Email szschaler@acm.org
Phone +44 (020) 7848 1513
WWW   www.steffen-zschaler.de

**Comment by casperdcl** [comment] 2019-09-05 10:03
not sure if you're talking about latest container, image, or both

**Comment by szschaler** [comment] 2019-09-05 12:10
Container. If the images differ, that will be picked up by the build process anyway…

Steffen

Dr. rer. nat. Steffen Zschaler AHEA

Senior Lecturer
King's College London
Department of Informatics

Visiting Scientist
The Francis Crick Institute

Email szschaler@acm.org
Phone +44 (020) 7848 1513
WWW   www.steffen-zschaler.de

**Comment by casperdcl** [comment] 2019-09-05 12:23
ah but if there are two different containers with the same name then they'll overwrite each other resulting in a lot of re-building due to cache misses.

**Comment by casperdcl** [comment] 2019-09-05 12:24
*images

**Comment by szschaler** [comment] 2019-09-05 12:26
I *think* docker-compose manages that…

Steffen

Dr. rer. nat. Steffen Zschaler AHEA

Senior Lecturer
King's College London
Department of Informatics

Visiting Scientist
The Francis Crick Institute

Email szschaler@acm.org
Phone +44 (020) 7848 1513
WWW   www.steffen-zschaler.de

**Comment by casperdcl** [comment] 2019-09-05 12:28
yes we'd have to document/warn about specifying a different image name in `docker-compose.override.yml` when managing multiple different images

**Comment by szschaler** [comment] 2019-09-05 12:44
I thought docker-compose names images by default using <project>_<service>_<index>_<slug>. If I’m not mistaken, <project> defaults to the name of the current directory, so images compiled from different directories are named differently by default.

Steffen

Dr. rer. nat. Steffen Zschaler AHEA

Senior Lecturer
King's College London
Department of Informatics

Visiting Scientist
The Francis Crick Institute

Email szschaler@acm.org
Phone +44 (020) 7848 1513
WWW   www.steffen-zschaler.de
